name: Build and Deploy Chat App to Azure

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    env:
      ConnectionStrings__DefaultConnection: ${{ secrets.AZURE_SQL_CONNECTION_STRING }}
      Azure__SignalR__ConnectionString: ${{ secrets.AZURE_SIGNALR_CONNECTION_STRING }}
      Azure__CognitiveServices__Endpoint: ${{ secrets.COGNITIVE_SERVICES_ENDPOINT}}
      Azure__CognitiveServices__ApiKey: ${{ secrets.COGNITIVE_SERVICES_APIKEY}}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'

      - name: Restore dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build --configuration Release --no-restore

      - name: Publish
        run: dotnet publish --configuration Release --output ./publish
      
      - name: Login to Azure
        uses: azure/login@v2
        with:
          creds: '${{ secrets.AZURE_CREDENTIALS }}'
      
      - name: Add App Settings
        uses: azure/appservice-settings@v1
        with:
          app-name: 'KikonoChatApp'
          app-settings-json: '${{ secrets.APP_SETTINGS }}'
          mask-inputs: true
          
      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'KikonoChatApp'
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          package: ./publish
